name: sos_app
description: "SOS Emergency app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  vibration: ^1.8.4
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  provider: ^6.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  internet_connection_checker: ^1.0.0+1
  dio: ^5.4.2+1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.0.8
  video_player: ^2.8.6
  action_slider: ^0.7.0
  url_launcher: ^6.2.6
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.4
  otp_pin_field: ^1.2.9
  flutter_local_notifications: ^17.2.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


